### ISSUE TITLE
Dudas sobre Python 🐍

### ISSUE THREAD

**Issue by ricardomiron** [CodeandoMexico/hacking-civico#12]
Si tienes alguna duda sobre los conceptos básicos de programación 💻  o Python en específico puedes comentarlas aquí ⬇️ . También siéntete libre de ayudar a tus compañeros respondiendo si sabes resolver su duda 😄

**Comment by shan-david** [comment]
Seguí el ejercicio de listas a la par del vídeo, y tuve problemas en la parte de hacer la lista de escolaridad. La tabla la pude hacer pero al momento de querer iterar los ciclos no podía. 
Es decir quise replicar el ejemplo:
Periodo: 2017
# Árboles: 428

Pero con los datos de la tabla de escolaridad, pero sólo logré que se reflejaran los datos de las primeras dos columnas, el de la tercera no me salía, no sé cómo se tiene que escribir el código para que se impriman esos datos. Es decir, puse las funciones pero los datos me salieron así:

periodo: 2017
# estudiantes: 38500
proporcion 2

En proporción tendría que ser el dato del porcentaje de la tercera columna, pero no los reconoce. Los datos en la tabla los puse:
         ['2015', 256000, '46.0'],
         ['2016', 330000, '48.5'],
         ['2017', 38500, '56.3'],
         ['2018', 476000, '49.0'],
         ['2019', 604000, '57.2'],
         ['2020', 870000, '62.4']

**Comment by RodolfoFerro** [comment]
Hola @shan-david, si tienes una lista como la esta 👇🏼 

```python
escolaridad = [
   ['2015', 256000, '46.0'],
   ['2016', 330000, '48.5'],
   ...
]
```

Puedes usar un ciclo `for` e imprimir los datos como sigue:

```python
# El siguiente código va dentro de un ciclo for
print("Periodo:", escolaridad["Periodo"])
print("No. de jóvenes:", escolaridad["Jóvenes (18-29)"])
print("Porcentaje:", escolaridad["% con estudios universitarios"])
print()
```

**Comment by shan-david** [comment]
Es que le sigo intentando, incluso copiando el código propuesto, pero lo que no puedo es que me reconozca los datos de la tercera columna. Es decir, sí me imprime bien período y no. de jóvenes. pero cuando el ciclo de porcentaje me marca error. 
**print("Periodo:", escolaridad[2][0])
print("No. de jóvenes:", escolaridad[2][1])**
(Estos dos salen bien)

_print("Porcentaje:", escolaridad[2][1][3])_
Este es el que no sé cómo ponerlo para que me reconozca los datos de la tercera columna

**Comment by RodolfoFerro** [comment]
@shan-david ¡Ah, pues entonces ya lo tienes!

Nota que si estos ya te funcionan bien 👇🏼 
```python
print("Periodo:", escolaridad[2][0])
print("No. de jóvenes:", escolaridad[2][1])
```

Entonces sólo debes cambiar el índice correspondiente:
```python
print("Porcentaje:", escolaridad[2][2])
```

Nota que tú mencionas
> print("Porcentaje:", escolaridad[2][1][3])
> Este es el que no sé cómo ponerlo para que me reconozca los datos de la tercera columna

Pero allí estás intentando utilizar el índice 3 para una cuarta columna que no existe. Ojo con usar el índice 2 para la tercer columna, pues 0 -> primer columna, 1 -> segunda columna, 2 -> tercer columna.

**Comment by shan-david** [comment]
¡Ya pude! Es que me estaba costando entender un poco el código :) gracias

**Comment by shan-david** [comment]
Otra vez tuve un problema al intentar hacer el ejercicio de esta semana.
Cargué el Notebook para el ejercicio de COVID, seguí todos los pasos, cargué los archivos, y fui corriendo todos los códigos tal cual como venían.
De pronto cuando llegué a la parte para hacer los merge, pude hacer bien los de los estados, pero cuando llegué al de other_col me marcó error, y de pronto me dejó de reconocer los demás catálogos y me sale esto:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-6f2f807d8b2d> in <module>()
      2 data = (
      3     # unimos con el catálogo MUNICIPIOS y ENTIDADES
----> 4     data.merge(catalogues['de ENTIDADES'], how='left', left_on='entidad_res', right_on='clave_entidad').
      5     drop(columns=['entidad_res', 'abreviatura']).
      6     rename(columns={'entidad_federativa':'entidad_res'}).

3 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in _maybe_coerce_merge_keys(self)
   1144                     inferred_right in string_types and inferred_left not in string_types
   1145                 ):
-> 1146                     raise ValueError(msg)
   1147 
   1148             # datetimelikes must match exactly

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat


Ya abrí dos archivos distintos para intentarle y me sigue marcando lo mismo, ¿qué es lo que debo corregir?

**Comment by RodolfoFerro** [comment]
Hola @shan-david, como @ricardomiron menciona acá https://github.com/CodeandoMexico/hacking-civico/issues/15#issuecomment-684907027, la secretaría realizó algunos cambios con los datos, entonces el [notebook](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/05_Exploracion_de_datos.ipynb) ahora tiene un problema por los tipos de datos justo en la celda que realiza el merge (la que te marcó el error). 

Danos oportunidad de solucionarlo verificando los datos y sus tipos, pero por ahora puedes omitir esa celda y continuar con las posteriores sin problema alguno. 👍🏼

**Comment by shan-david** [comment]
> Hola @shan-david, como @ricardomiron menciona acá [#15 (comment)](https://github.com/CodeandoMexico/hacking-civico/issues/15#issuecomment-684907027), la secretaría realizó algunos cambios con los datos, entonces el [notebook](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/05_Exploracion_de_datos.ipynb) ahora tiene un problema por los tipos de datos justo en la celda que realiza el merge (la que te marcó el error).
> 
> Danos oportunidad de solucionarlo verificando los datos y sus tipos, pero por ahora puedes omitir esa celda y continuar con las posteriores sin problema alguno. 👍🏼


Usé el nuevo Notebook y ya subí mi ejercicio, pero tuve un problema para poder sacar el número de casos positivos por estado, al parecer ese es el catálogo que tiene problemas.

Usé dos versiones del código:
_data.groupby('entidad_res').resultado.value_counts(), 
data.groupby(['entidad_res','resultado'])['id_registro'].count()_
Y sólo me sacaba los primeros dos y los últimos dos estados, probé con otras combinaciones del código como 

_data[data.resultado == '1'].entidad_res.value_counts().sort_index()_ [puse número en vez de positivo porque el catálogo no se cargó] y me salió la leyenda
 _/usr/local/lib/python3.6/dist-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)
Series([], Name: entidad_res, dtype: int64)_

**Comment by Glaydyesther** [comment]
***Hola chic@s no es una pregunta de python pero no me da acceso a la página de Aprende León, me aparece esto***
***
![Imagen1](https://github.com/Glaydyesther/hacking-civico/blob/master/Captura%20de%20pantalla%20(76).png)

***Si doy clic en seguir la página me envía a una encuesta de "Supuestamente Google" para hacerme acreedora de un Samsung" :( ¿Podrían apoyarme?***
***
***Pero si me permite ingresar a cualquier otra página normalmente***
![Imagen2](https://github.com/Glaydyesther/hacking-civico/blob/master/Captura%20de%20pantalla%20(78).png)
***Incluso me permite ingresar normal a Github***

**Comment by RodolfoFerro** [comment]
Hola @Glaydyesther, posiblemente haya algún tema con el certificado de seguridad (SSL) de la plataforma de manera que tu antivirus lo detecte como un sitio no seguro. Si estás segura de que estás accediendo al sitio correcto (https://aprendeleon.com/) entonces puedes darle a la opción de "Aceptar el riesgo".

**Comment by Glaydyesther** [comment]
@RodolfoFerro Ese es el problema, cuando doy en la opción "Aceptar el riesgo" me envía directo a la publicidad de "Google" y de nuevo no me permite acceder. Ya hasta desinstalé mi antivirus y ni así. Incluso ingresé al link que adjuntaste y me marca de nuevo la nota que la página no es confiable.

**Comment by RodolfoFerro** [comment]
@Glaydyesther Una opción es que intentemos con otro navegador, yo lo estoy abriendo desde Chrome sin problemas. 🤔

**Comment by Glaydyesther** [comment]
@RodolfoFerro  Lo intenté abrir con Chrome y después con Edge , me siguió dando el mismo resultado en ambos. Y ya no sé qué más hacerle. Puedo ingresar a Github sin ningún problema.

**Comment by RodolfoFerro** [comment]
Ya @ricardomiron está al tanto y se está coordinando con el equipo de comunicación del municipio para que verifiquen el sitio. Por acá estaremos compartiendo si hay algún movimiento y qué solución nos dan a esto.

**Comment by Glaydyesther** [comment]
Muchas gracias. Estaré al pendiente 🙂

**Comment by ricardomiron** [comment]
> Muchas gracias. Estaré al pendiente 🙂

Hola @Glaydyesther parece que ya está resuelto el problema.

**Comment by Glaydyesther** [comment]
Lo he revisado, muchas gracias y en efecto ya está resuelto 👍

**Comment by shan-david** [comment]
Hola, buenos días,

Estoy trabajando en el proyecto final y estoy trabajando con una base de datos que tiene fechas, pero al momento de querer graficar los datos me marca el siguiente error:

TypeError: Object of type 'time' is not JSON serializable

No sé qué debo hacer para evitar esta falla, no sé si me puedan asesorar. 

Gracias :)

**Comment by RodolfoFerro** [comment]
Hola @shan-david, resulta que si quieres serializar objetos en un objeto JSON utilizando Python, dichos objetos deben ser tipos primitivos, esto es, los elementos deben ser de tipo `int`, `float`, etc.

Si el error que te arroja es el siguiente:
```python
TypeError: Object of type 'time' is not JSON serializable
```

Te recomiendo que el formato de fecha que tienes en Python lo conviertas a un `str` antes de querer exportar el objeto JSON. :)

**Comment by davseg** [comment]
Hola @RodolfoFerro y @ricardomiron! Espero se encuentren bien.

De antemano, una disculpa por escribir en fin de semana. Sin embargo, tengo un problema técnico con el proyecto final que no he logrado solucionar.

El fin de semana pasado (imagen 1 y 2) estaba concluyendo mi análisis del entorno emprendedor en Hidalgo pero lo pause debido al trabajo. Hoy que planeaba finalizarlo, me encuentro con que el Google Collab está completamente vacio (imagen 3) y sin historial de versiones (imagen 4).

No sé si tenga que ver con que el lunes se apagó de golpe mi laptop (debo mantenerla siempre conectada porque ya no funciona la bateria) pero me sorprende ya que el sábado y domingo podía visualizar mi proyecto sin ningún problema desde Google Drive y Github. Saben si hay alguna forma de recuperar el archivo? Lo he intentado todo la tarde por mi cuenta y con ayuda de algunas pistas en Stackoverflow ([link1](https://stackoverflow.com/questions/55036559/how-to-autosave-notebooks-in-google-colab), [link2](https://stackoverflow.com/questions/41156741/is-it-possible-to-get-back-the-jupyter-editing-when-my-browserchrome-crashes) y [link3](https://stackoverflow.com/questions/58616119/how-to-recover-unsaved-code-in-google-colab)) pero no he tenido éxito :(

Sé que ya pasó la fecha de entrega. No obstante, me interesaba terminarlo porque estaba obteniendo grandes hallazgos y quería aplicar los últimos temas de scrapeo y la generación de API´s

![image](https://user-images.githubusercontent.com/53650619/96359471-d6f08780-10d8-11eb-88b2-8c49e302c14b.png)
![image](https://user-images.githubusercontent.com/53650619/96359474-dd7eff00-10d8-11eb-9b91-fe0a275078f8.png)
![image](https://user-images.githubusercontent.com/53650619/96359479-ea035780-10d8-11eb-859b-7668a930966b.png)
![image](https://user-images.githubusercontent.com/53650619/96359482-f25b9280-10d8-11eb-952d-5c793762d6cc.png)

**Comment by RodolfoFerro** [comment]
Hola @davseg, pudieron haber sucedido varias razones. ¿Abriste Colab desde tu Google Drive, desde GitHub o desde colab.research.google.com?
- Si lo abriste desde Google Drive, puede ser que debido a que tu lap se apagó de golpe no hayas podido guardar el cuaderno.
- Si lo abriste desde un cuaderno en GitHub, debes crear una copia para poder guardar cambios en Drive y/o guardarlos en tu repo de GitHub. (No se exporta a GitHub hasta que tú lo haces.)
- Si lo abriste desde el sitio de Colab, se supone que se guarda en tu carpeta de `Colab Notebooks` en Drive, sin embargo si no aparece, puede suceder lo mismo que en el primer caso.

¿Tu situación recae en alguno de estos tres casos? Sigo pendiente. 👍🏼

**Comment by davseg** [comment]
@RodolfoFerro gracias por tu pronta respuesta!

Originé el archivo desde el sitio de Colab e inmediatamente mandé una copia a mi Github, de tal modo que el archivo me aparecía en los 3 sitios (página de Colab, carpeta individual de Google Drive y Github). Igual no sé si influya en algo, pero recuerdo que a la hora de tener un par de archivos Colab abiertos desde la página, el logo desplegado en la pestaña de mi proyecto estaba en color rojo mientras el del resto de las pestañas era color naranja.

Tomando en cuenta lo que me platicas, parece imposible recuperarlo. Vaya forma de aprender la lección :(

![image](https://user-images.githubusercontent.com/53650619/96532834-52297900-1252-11eb-9a66-7e995c5a152e.png)
