### ISSUE TITLE
Ejercicios para Ruta Coder [Notebooks] 📓

### ISSUE THREAD

**Issue by ricardomiron** [CodeandoMexico/hacking-civico#14]
Hemos creado cuatro _notebooks_ que abarcan los diferentes conceptos del tema **Python 101​: Introducción al código** para que puedan practicar y aplicar los conceptos vistos en los videos.

1. [Variables y operadores](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/01_Variables_y_operaciones.ipynb)
2. [Condicionales y ciclos](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/02_Condicionales_y_ciclos.ipynb)
3. [Colecciones](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/03_Colecciones.ipynb)
4. [Funciones y módulos](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/04_Funciones_y_m%C3%B3dulos.ipynb)
5. [Exploración de datos](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/05_Exploracion_de_datos.ipynb)
6. [Anatomía de un gráfico](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/06_Anatom%C3%ADa_de_un_gr%C3%A1fico.ipynb)
7. [Gráficos simples](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/07_Gr%C3%A1ficos_simples_con_Altair.ipynb)
8. [Gráficos complejos](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/08_Gr%C3%A1ficos_complejos_con_Altair.ipynb)
9. [Compartir tus gráficos](https://github.com/CodeandoMexico/hacking-civico/blob/master/notebooks/09_Compartir_tus_gr%C3%A1ficos.ipynb)

Puedes abrirlos directamente en Google Colab usando el botón que se encuentra en la parte superior y crear tu propia copia para poder modificarlo y realizar los ejercicios, también puedes sincronizarlo con GitHub en tu Fork del repositorio del curso en la carpeta de `notebooks`.

**Comment by MadriD2ev** [comment]
Hola :smiley:, tengo problemas para guardar en mi fork una copia de lo que estoy haciendo en google Colab. Realicé los siguientes pasos: Archivo -> Guardar una copia en GitHub -> Autoricé la colaboración y el acceso a mis repositorios -> y en copiar en GitHub solo aparecen los repositorios de CodeandoMexico/hacking-civico :confused: 

<img width="878" alt="Captura de Pantalla 2020-08-27 a la(s) 12 13 53 a  m" src="https://user-images.githubusercontent.com/68882204/91387296-95d7a780-e7fa-11ea-9017-c23efc0f9423.png">

:grinning: también se me ocurrió ir a Archivo -> Ver en GitHub (solo porque me dio curiosidad :neutral_face:) y me envía al repositorio original:sweat_smile:

:eyes: ¿Podrían ayudarme y decirme en qué me equivoqué :see_no_evil: ? De cualquier modo guarde copia en Drive y mañana volveré a leer haber que más puedo hacer.

Gracias :raising_hand:

**Comment by MadriD2ev** [comment]
Lamento molestar de nuevo pero creo ya hice algo muy malo en los repositorios, bueno eso creo pero no entiendo el por qué. Ayer estaba viendo los videos en la plataforma, hice un pull resquest por el notebooks de los ejercicios en python e hice la primera parte, por ahí comenté que no pude hacer la copia en mi fork dentro del issue de ejercicios para phyton. El caso es que ahorita estoy tratando de continuar con los ejercicios y ya no aparecen ni en el directorio raíz ni en mi fork. Tengo la incertidumbre si fue por algo que hice mal y que mis compañeros no puedan tener acceso a ellos. Ojalá pudieras apoyarme con esto @ricardomiron

**Comment by ricardomiron** [comment]
> Hola 😃, tengo problemas para guardar en mi fork una copia de lo que estoy haciendo en google Colab. Realicé los siguientes pasos: Archivo -> Guardar una copia en GitHub -> Autoricé la colaboración y el acceso a mis repositorios -> y en copiar en GitHub solo aparecen los repositorios de CodeandoMexico/hacking-civico 😕
> 
> 😀 también se me ocurrió ir a Archivo -> Ver en GitHub (solo porque me dio curiosidad 😐) y me envía al repositorio original😅
> 
> 👀 ¿Podrían ayudarme y decirme en qué me equivoqué 🙈 ? De cualquier modo guarde copia en Drive y mañana volveré a leer haber que más puedo hacer.
> 
> Gracias 🙋

Hola Madrid, esto pasa porque intentaste guardar una copia en GitHub directamente desde el notebook original que está ligado al repo original, si bien puedes correrlo y modificar el notebook no te dará permiso de guardar cambios. Lo primero que tienes que hacer es guardar una copia en tu Drive y ya una vez que estés en la copia del notebook a  la hora que quieras guardarlo en GitHub ya te aparecerán los repos de tu usuario.

**Comment by ricardomiron** [comment]
> Lamento molestar de nuevo pero creo ya hice algo muy malo en los repositorios, bueno eso creo pero no entiendo el por qué. Ayer estaba viendo los videos en la plataforma, hice un pull resquest por el notebooks de los ejercicios en python e hice la primera parte, por ahí comenté que no pude hacer la copia en mi fork dentro del issue de ejercicios para phyton. El caso es que ahorita estoy tratando de continuar con los ejercicios y ya no aparecen ni en el directorio raíz ni en mi fork. Tengo la incertidumbre si fue por algo que hice mal y que mis compañeros no puedan tener acceso a ellos. Ojalá pudieras apoyarme con esto @ricardomiron

Parece que todo está bien, no veo que haya hecho algo mal, tu fork está actualizado. 

Pero ten en cuenta que aunque los notebooks estén en tu fork por el Pull Request que hiciste, siguen teniendo la referencia a los originales por lo que de nuevo si quieres poder modificarlos y guardar los cambios tendrás que hacerlo con una copia en tu Drive. 

Los cambios que hagas en esa copia no se guardarán automáticamente en tu repositorio GitHub, lo que te recomiendo es que completes los cuadernos en tu copia de Drive y una vez que lo tengas terminado, hagas una copia en tu fork de GitHub de este mismo con el mismo nombre del original, esto hará que _reemplaces_ el que estaba por tu copia ya con los cambios/ modificaciones que hayas hecho.

<img width="1233" alt="Captura de Pantalla 2020-08-27 a la(s) 11 54 47" src="https://user-images.githubusercontent.com/18178248/91472013-75403980-e85c-11ea-834a-8e203bf2a249.png">

**Comment by MadriD2ev** [comment]
Muchas gracias @ricardomiron :smiley: ya hice lo que mencionaste primero sobre la copia en Drive y ahora ya puedo ver los ejercicios, me parece que como tenía conflictos no me dejaba continuar.  :octocat:

**Comment by escorpioh** [comment]
Hola. Ya resolví los ejercicios. Los envíe como un Patch de mi Fork al repositorio principal en la sección de Notebooks. ¿Eso es válido o ya metí la pata y afecté a los otros usuarios?

Muchas gracias, saludos.
