### ISSUE TITLE
Sesión de preguntas y retroalimentación 🗣

### ISSUE THREAD

**Issue by ricardomiron** [CodeandoMexico/hacking-civico#16]
Tendremos una sesión de retroalimentación intermedia para los temas de Python 101 y exploración de datos el próximo jueves a través de videollamada 📹 con los instructores en caso de que tengas alguna duda o quieras retroalimentación.  Es opcional.

**Fecha**: Jueves 3 de septiembre de 2020.
**Hora**: 7:00 pm - 8:00 pm
**Plataforma**: Google Meet
**Enlace de acceso**: [https://meet.google.com/mgq-msot-pba](https://meet.google.com/mgq-msot-pba)

*️⃣ Adicionalmente puedes poner en los comentarios cualquier duda que tengas en caso de que no puedas unirte a la reunión.

**Comment by RodolfoFerro** [comment]
### Recurso sobre Pandas 🐼 

¡Hola! 

Si es de utilidad para algunas personas, este es un post introdutorio a Pandas, de un sitio que me gusta mucho seguir: https://stackabuse.com/python-with-pandas-dataframe-tutorial-with-examples/

Justamente, este post es la conexión directa que nos permite pasar de listas a dataframes. 👌🏼

**Comment by ricardomiron** [comment]
Hola tuvimos que recorrer la sesión una hora más tarde **(ahora será de 7pm a 8pm)** para que los instructores invitados tengan más tiempo de acompañarnos.

**Comment by jballesterosc** [comment]
¡Hola!

Traté de abrir el curso desde Aprende León y me redirecciona directo a esto:
![Captura de Pantalla 2020-09-05 a la(s) 21 04 34](https://user-images.githubusercontent.com/68790102/92316564-98d15580-efbb-11ea-9821-3a940dff4fb0.png)

No encuentro otra forma de acceder.

**Comment by ricardomiron** [comment]
> ¡Hola!
> 
> No encuentro otra forma de acceder.

Hola @jballesterosc ya debería estar funcionando 👍
