### ISSUE TITLE
Tarea 1 – Ejemplos de proyectos que usen datos abiertos

### ISSUE THREAD

**Issue by WAYO-BAYO-9631** [CodeandoMexico/hacking-civico#2]
Tarea 1 – Ejemplos de proyectos que usen datos abiertos

Instrucciones: Buscar un ejemplo de un proyecto que haya hecho uso de datos abiertos, este puede ser tecnológico o no.
•	¿Cuál fue el proyecto? Pon su título, una breve descripción y la fuente de consulta.
R= Observatorio Ciudadano de Hechos de Tránsito de la Zona Metropolitana de Mérida: El Observatorio Ciudadano de Hechos de Tránsito de la Zona Metropolitana de Mérida es una herramienta para la investigación y la toma de decisiones de política pública relacionadas a la seguridad vial.
Fuente: El Observatorio de Movilidad Sostenible de Mérida (OMSM) https://movilidadmerida.org/ocht/
•	 ¿En dónde y cuándo se realizó este proyecto? 
R= Este Observatorio consiste en una mapa digital en el que se encuentran ubicados los hechos de tránsito ocurridos en la Zona Metropolitana de la Ciudad de Mérida, Yucatán, México, durante el año 2015 y 2016.
•	 ¿Qué proyecto con datos se te ocurre que podría implementarse en tu ciudad?
R=  Como el Observatorio de Movilidad Sostenible de Mérida (OMSM) tiene la finalidad de que se instale a corto plazo tanto en la ciudad de Mérida, como en todo el estado “El Observatorio Nacional de Lesiones Rama Yucatán”; se podría hacer un proyecto de solicitud ciudadana para que este mismo año dicho Observatorio Nacional vea la luz  iniciando con un programa de zonificación de Covid-19, sus áreas de impacto y disminuir su propagación mediante una rezonificación de los paraderos de autobuses y taxis en la ciudad a zonas de menor afluencia peatonal, y en el caso del centro histórico y sus aras turístico comerciales, trasladar éstos paraderos a parques y explanadas con vigilancia policiaca o guardias privados con el fin de que los usuarios de dichos servicios cumplan con las restricciones sanitarias del cubre bocas y sana distancia para lograr el decrecimiento de la curva de contagio de Covid-19 que azota al estado, y de no ser así ser acreedores a multas acumulables, con incrementos escalonadas por reincidencia sanitaria, y de cobros íntegros sin derecho a reducciones o descuentos algunos, así como instalar “Módulos Cívicos de Reeducación Ciudadana”  (integrados por voluntarios de la sociedad civil, académicos, empresarios y sector salud gubernamental; con la finalidad de informar, concientizar e instruir a la población de los datos reales de la crisis pandémica global, nacional y estatal, así como de las correctas prácticas para manejos de la crisis sanitaria por parte de los cuidados y en caso de los “Reincidentes Sanitarios” obligarlos a tomar cursos que deberán de ser acreditados mediante exámenes teórico/prácticos, como se da en el caso de la obtención de la licencia de manejo o como en USA para los que sufren la enfermedad de ira al volante, por ejemplificar la idea.  Si bien el fin del programa es únicamente el monitoreo de accidentes viales, podría aprovecharse el mismo para otros fines, como el de prevención de accidentes viales casos extraordinarios, como serían los riesgos sanitarios, provisionalmente el monitoreo de casos de Covid-19 en el transporte público de ésta ciudad y demás estados del país.

                           WAYO-BAYO-9631.                         03/08/2020.                          eduardo.sesma@inaipyucatan.org.mx

**Comment by MadriD2ev** [comment]
- ¿Cuál fue el proyecto? 
   Nombre del proyecto: Serendipia.
   Es una iniciativa de periodismo de datos. En este portal son publicadas investigaciones y herramientas basadas en datos  abiertos e información obtenida por medio de mecanismos de acceso a la información pública.
[https://serendipia.digital/que-es-serendipia/ ](url)

-  ¿En dónde y cuándo se realizó este proyecto?
Las investigaciones de Serendipia tienen sustento en bases de datos, trabajo en terreno y metodología periodística potencializados por visualizaciones creadas para facilitar la comunicación de los temas.

Publicamos una investigación mensual y notas semanales.

-  ¿Qué proyecto con datos se te ocurre que podría implementarse en tu ciudad?
En la ciudad en la que me encuentro sus actividades económicas en su mayoría serían el comercio en pequeñas y medianas empresas, la educación y el transporte público. Se me ocurre que en un intento de apoyar a la economía municipal en el sector del transporte público específicamente taxis se podría desarrollar y/o solicitar información respecto a ellos. De este modo el usuario final pudiera estar seguro que está tomando una unidad debidamente registrada y de esta forma brindar un sentido de confianza, que los dueños de esas unidades tuvieran la oportunidad de ofrecer un mejor servicio a los usuarios y como un acción colateral a esto intentar disminuir en algo las insidencias delictivas.
