### ISSUE TITLE
Ruta Hacker [ya disponible] 🔔

### ISSUE THREAD

**Issue by ricardomiron** [CodeandoMexico/hacking-civico#21]
🔔 Estimados estudiantes.

Ya pueden consultar la primera parte de la [Ruta Hacker](https://aprendeleon.com/course/ruta-hacker/) en Aprende León.

**Comment by shan-david** [comment]
Buenos días, una duda, ¿de la ruta hacker sólo son los dos vídeos de web scrapping?

Gracias :)

**Comment by ricardomiron** [comment]
@shan-david No, espero que la parte de APIs y mapas ya esté arriba el lunes :)

**Comment by MadriD2ev** [comment]
Hola @ricardomiron de la ruta Hacker solo pude ver el video 1 Web Scraping y estructura web, posteriormente ya me marco como respuesta del servidor un 503.

![503](https://user-images.githubusercontent.com/68882204/95915516-d79dbc80-0d6c-11eb-9652-e8f3510b5226.png)

Espero tus comentarios, saludos.

**Comment by ricardomiron** [comment]
@MadriD2ev aún te aparece como no disponible?

**Comment by MadriD2ev** [comment]
Hola @ricardomiron ya pude acceder a los videos, gracias 😃
