### ISSUE TITLE
Datos Geoespaciales

### ISSUE THREAD

**Issue by jballesterosc** [CodeandoMexico/hacking-civico#22]
Hola 👋, 

He estado muy pendiente del apartado de _datos geoespaciales_ pero actualmente sólo hay un video disponible. ¿Si se subirán más o en definitiva es el último? 😢

**Comment by ricardomiron** [comment]
Hola @jballesterosc , sí ya están listos los otros videos pero creo que se subirán hasta la próxima. Les te avisamos cuando estén disponibles :)
