### ISSUE TITLE
#3 

### ISSUE THREAD

**Issue by RaquelQuiroz** [CodeandoMexico/hacking-civico#7]

**Comment by RodolfoFerro** [comment]
Hola @RaquelQuiroz, ¿añadirás algo de contenido por acá?

En caso de que haya sido un issue creado por accidente, podemos proceder a cerrarlo. En caso contrario porfa avísanos para esperar por el contenido, ¡saludos!

**Comment by RaquelQuiroz** [comment]
Hola, si fue un error, una disculpa, por favor procedan a cerrarlo,
gracias.
