### ISSUE TITLE
Tarea 1

### ISSUE THREAD

**Issue by josantgl** [CodeandoMexico/hacking-civico#8]
# Tarea 1.
## Proyecto: Base de datos de Incidencia delictiva del Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública.
La base de datos comparte información referente a incidencia delictiva: estadísticas, _archivos de datos abiertos_, así como información relevante al respecto. La **incidencia delictiva** se refiere a la presunta ocurrencia de delitos registrados en averiguaciones previas iniciadas o carpetas de investigación, reportadas por las Procuradurías de Justicia y Fiscalías Generales de las entidades federativas en el caso del fuero común y por la Procuraduría General de la República en el fuero federal.

Fuente: [Indencia delictiva](https://www.gob.mx/sesnsp/acciones-y-programas/incidencia-delictiva-87005?idiom=es)

![Incidencia delictiva Logo](https://www.gob.mx/cms/uploads/action_program/main_image/13469/post_outstanding_bANNER.jpg)¡

## ¿En dónde y cuándo se realizó ese proyecto? <h2>

La información se realizó por la obligación de transparencia del Sistema Nacional de Seguridad Pública. La base tiene datos nacionales desde 1997.

## ¿Qué proyecto con datos se te ocurre que podría implementarse en tu ciudad? <h2>

Se desea realizar el proyecto de **_Red de inteligencia comunitaria_** para compilar datos de incidencia delictiva a nivel de colonias del municipio de tal manera que esta información contribuya para mejorar las estrategias de prevención de violencias, así como disminuir el rezaga en la cifra negra de delitos.

**Comment by ricardomiron** [comment]
Hola @josantgl , gracias por tu aportación. Veo que ya comentaste el Issue abierto #3  en donde está el mismo contenido, no es necesario crear nuevos para las entregas.

Saludos.
