### ISSUE TITLE
Ruta Coder [ya disponible] 🔔 

### ISSUE THREAD

**Issue by ricardomiron** [CodeandoMexico/hacking-civico#9]
🔔  Estimados estudiantes. 

Hemos decidido aplazar la apertura de la [Ruta Coder](https://aprendeleon.com/course/ruta-coder/) ⌨️  a este **viernes (14 de agosto)** para compensar un poco el retraso de la _Ruta Cívica_ ⚡️  y darles chance de terminar ya que la mayoría aún no ha realizado las actividades de la misma y nos interesa que la mayoría del grupo vaya a la par para poder formar los equipos para los proyectos. 😄 

> Esto NO afectará el calendario general, sino que en lugar de ir subir el contenido a inicio de la semana lo haremos completo a finales de la misma, asegurándonos que tengan tiempo suficiente para completarla.

**Comment by escorpioh** [comment]
Enterado, muchas gracias.

**Comment by dcanulr** [comment]
Ya está habilitado la Ruta Coder en la plataforma de aprendeleon? No lo encuentro 😢

**Comment by ricardomiron** [comment]
> Ya está habilitado la Ruta Coder en la plataforma de aprendeleon? No lo encuentro 😢

Hola @dcanulr , se encuentra [aquí](https://aprendeleon.com/course/ruta-coder/). Cada ruta está contenida en su propia sección en Aprende León

**Comment by MarcelaMosino** [comment]
Hola!

Yo tengo una duda, la ruta cívica es como un curso a parte del que ya terminamos 14/14 
¿Tenemos que dar en *finalizar el curso*?, ¿o eso hasta que terminemos las tres rutas?

**Comment by lcinthya** [comment]
> > Ya está habilitado la Ruta Coder en la plataforma de aprendeleon? No lo encuentro 😢
> 
> Hola @dcanulr , se encuentra [aquí](https://aprendeleon.com/course/ruta-coder/). Cada ruta está contenida en su propia sección en Aprende León

Yo también tengo la duda ya que el contenido no esta disponible , en mi caso veo el listado de temas pero me aparece bloqueado.

![image](https://user-images.githubusercontent.com/49242544/90699375-bfb42b80-e248-11ea-880c-81437b245550.png)

No se si en mi caso sea porque no tengo la ruta Civica terminada al 100% ya que no puedo marcar como concluidas las tareas pues no me aparece el  scroll del lado derecho para ver el botón de finalizar/concluir

![image](https://user-images.githubusercontent.com/49242544/90699605-5680e800-e249-11ea-8548-ecdf1e24f058.png)

**Comment by ricardomiron** [comment]
La **Ruta Coder** se encuentra en su propia sección @lcinthya dentro de la sección general del curso: https://aprendeleon.com/cursos/datos-abiertos-y-hacking-civico/

![Captura de Pantalla 2020-08-19 a la(s) 18 34 00](https://user-images.githubusercontent.com/18178248/90700153-ad3af180-e24a-11ea-8762-dfbe6843bf5d.png)

**Comment by lcinthya** [comment]
Hola de nuevo , efectivamente veo la  Ruta Coder en su  sección, el problema es que no puedo acceder a los vídeos, como mostré en la imagen de mi comentario anterior justo al lado de cada uno de los temas de esta ruta me aparece un candidato y aunque veo el titulo del tema no me permite dar click para revisar el tema.

**Comment by ricardomiron** [comment]
> Hola de nuevo , efectivamente veo la Ruta Coder en su sección, el problema es que no puedo acceder a los vídeos, como mostré en la imagen de mi comentario anterior justo al lado de cada uno de los temas de esta ruta me aparece un candidato y aunque veo el titulo del tema no me permite dar click para revisar el tema.

@lcinthya una disculpa no había visto bien la primera imagen, esto sucede por dos posibles razones:

1. La plataforma no mantiene la sesión activa por mucho tiempo aunque desafortunadamente no hay una indicación muy clara de esto, por lo que volver a iniciar sesión cada cierto tiempo, basta con volver a ingresar.

![Ruta Coder](https://user-images.githubusercontent.com/18178248/90712600-074aaf80-e269-11ea-82d6-4cb542a1ee3c.png)

2. Si tu sesión está activa y aún te aparecen los candados, significa que no le haz dado en iniciar al módulo, del lado superior derecho hay un botón azul que tendrá el mensaje **"Entrar/ Iniciar"** una vez que des clic en él ya deberá cambiar a "Continuar" y el contenido no tendrá candados. 

Espero sea útil, sino aquí andamos. 😄

**Comment by matahj** [comment]
Hola, yo puedo llegar hasta el video 3,
 
de ahí en adelante me aparece como en la imagen.

![imagen](https://user-images.githubusercontent.com/8812920/90822444-175e9f80-e2fa-11ea-959c-4465d50bed5d.png)

**Comment by ricardomiron** [comment]
> Hola, yo puedo llegar hasta el video 3,
> 
> de ahí en adelante me aparece como en la imagen.

Hola a todos, parece que es un problema de la plataforma, me comentan que hoy se resuelves y ya todos deberían de poder acceder al contenido. @matahj

**Comment by shan-david** [comment]
Acabo de checar y sigue el problema de la plataforma que en la ruta coder sólo sale hasta el tercer vídeo (pensé que era sólo yo la del problema pero ya vi que somos todos jeje)

**Comment by Glaydyesther** [comment]
Siii, yo también tengo el mismo problema. No puedo acceder, me dice estar con candado cada lección.

**Comment by ricardomiron** [comment]
@shan-david @Glaydyesther @matahj @lcinthya Ya está resuelto el problema, ya deberían poder acceder al contenido.

**Comment by shan-david** [comment]
@ricardomiron Tengo una duda, tomando en consideración el problema que hubo con los vídeos, y que eso nos retrasó a mucho, ¿habrá un ajuste con las fechas? Porque acabo de ver el correo de que ya está disponible la ruta coder, pero por cuestiones de trabajo no he podido avanzar con los vídeos que estuvieron disponibles el pasado miércoles :(

**Comment by ricardomiron** [comment]
> @ricardomiron Tengo una duda, tomando en consideración el problema que hubo con los vídeos, y que eso nos retrasó a mucho, ¿habrá un ajuste con las fechas? Porque acabo de ver el correo de que ya está disponible la ruta coder, pero por cuestiones de trabajo no he podido avanzar con los vídeos que estuvieron disponibles el pasado miércoles :(

No sé preocupen dejaremos abierto el contenido y los ejercicios/ tareas para que puedan tener más tiempo de completarlos.

**Comment by shan-david** [comment]
Otra duda con respecto a la Ruta Coder, ¿todavía no están disponibles los vídeos/materiales de "Visualización​: Resumir y comprender los datos" y "Proyecto: Sesión de definición"?

**Comment by EsquivelJC** [comment]
Quería comentar que ojalá sigan abiertas las tareas por un poco más de tiempo, este fin de semana me iba a dedicar a realizarlas, pero intenté ingresar a la página y parece que los hackearon. Y ojalá los de aprende león puedan arreglarlo pronto.

**Comment by ricardomiron** [comment]
> Quería comentar que ojalá sigan abiertas las tareas por un poco más de tiempo, este fin de semana me iba a dedicar a realizarlas, pero intenté ingresar a la página y parece que los hackearon. Y ojalá los de aprende león puedan arreglarlo pronto.

Hola, si ya reportamos el problema espero lo puedan solucionar pronto.

**Comment by ricardomiron** [comment]
> Hola, si ya reportamos el problema espero lo puedan solucionar pronto.

**Update**: ya está todo resuelto.
